project_name: gcp-vm-control
builds:
  - #
    env:
      - CGO_ENABLED=0
    main: .
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - #
    format_overrides:
      - # Which GOOS to override the format for.
        goos: windows
        # The format to use for the given GOOS.
        # Valid options are `tar.gz`, `tgz`, `tar.xz`, `txz`, tar`, `gz`, `zip`, `binary`, and `none`.
        # Default is `tar.gz`
        format: zip
signs:
  - #
    artifacts: binary
